eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: client1

server:
  port: 8091
nameProp: Value property "nameProp" from LOCAL application.yml