eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8888

spring:
  application:
    name: eureka1-consumer1

name_eureka1-service1: eureka1-service1
service1-ctrl1: http://${name_eureka1-service1}/ctrl1